name: NullTerrain
main: uk.me.elizabethmyers.nullterrain.NullTerrain
version: 0.3.1
website: http://elizabethmyers.me.uk/
author: Elizabeth Jennifer Myers
description: Terra Nullis for a specific world
load: startup
